from .attention import *
from .mobilenet import *
from .resnext import *
from .squeezenet import *
from .densenet   import *
from .mobilenetv2  import * 
from .rir import *          
from .stochasticdepth import *
from .googlenet  import *
from .nasnet import *       
from .senet  import *      
from .vgg import *
from .inceptionv3  import *
from .preactresnet import *  
from .shufflenet import *   
from .wideresidual import *
from .inceptionv4 import *
from .resnet import *  
from .shufflenetv2 import *
from .xception import *